Repository algosup/2024-2025-project-1-fpga-team-5, pull requests merged in 2024-10, with the labels that each got.

#12 Remove useless NPC from readme
  README.md
Labels: documentation, enhancement

#11 First playable version
  src/Go_Board_Constraints.pcf
  src/main.v
  src/modules/7_segments.v
  src/modules/debounce_switch.v
  src/sprites/car.v
  src/sprites/grass.v
  src/sprites/player.v
  src/sprites/road.v
Labels: enhancement

#15 Merging Test Plan
  Documents/Management/ProjectCharter.md
  Documents/TestPlan/TestPlan.md
  Documents/TestPlan/img/IntegrationTesting.png
  Documents/TestPlan/img/StressPerformanceTesting.png
  Documents/TestPlan/img/UnitTesting.png
  Documents/TestPlan/img/UserAcceptanceTesting.png
  Documents/UserManual/User Manual.pdf
  Documents/UserManual/UserManual.pdf
  Documents/UserManual/UserManualUpdate.md
  README.md
Labels: documentation

#26 Weekly report 5
  Documents/Management/WeeklyReports/Week5.md
Labels: documentation
